// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVtB0tIuRpi0qsJIPIschucHKNC9XkUQ',
    appId: '1:747318246901:web:384563a69b12f48a9874bc',
    messagingSenderId: '747318246901',
    projectId: 'tesis-rider-san-juan',
    authDomain: 'tesis-rider-san-juan.firebaseapp.com',
    storageBucket: 'tesis-rider-san-juan.firebasestorage.app',
    measurementId: 'G-VFT7HR2NDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsEiW11vXReGrEKHWIt_dpcMIxGnmpvQ',
    appId: '1:747318246901:android:c741b9129e785d9f9874bc',
    messagingSenderId: '747318246901',
    projectId: 'tesis-rider-san-juan',
    storageBucket: 'tesis-rider-san-juan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxxNiI90uQKfulUUYNAP4Ite7jDft2sI',
    appId: '1:747318246901:ios:3767c4d4eba299319874bc',
    messagingSenderId: '747318246901',
    projectId: 'tesis-rider-san-juan',
    storageBucket: 'tesis-rider-san-juan.firebasestorage.app',
    iosBundleId: 'com.example.busRiderApp',
  );
}
